### ISSUE TITLE
Android14报错

### ISSUE THREAD

**Issue by 390057892** [mayzs/paho.mqtt.android#2]
![image](https://github.com/mayzs/paho.mqtt.android/assets/23398269/a5b50f43-e827-41cf-80ba-ba00465f1731)

java.lang.SecurityException: Caller cn.tencent.mm needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.

**Comment by mayzs** [comment]
在 manifest 中添加android.permission.SCHEDULE_EXACT_ALARM ,android.permission.USE_EXACT_ALARM 这两个权限

**Comment by mayzs** [comment]
1.2.0 版本去除了这两个权限
