### ISSUE TITLE
FOREGROUND_SERVICE_DATA_SYNC、SCHEDULE_EXACT_ALARM两个权限能否去掉

### ISSUE THREAD

**Issue by yuhouzhizhu** [mayzs/paho.mqtt.android#3]
Google Play需要单独为这两个权限增加填写声明和录屏，这两个权限还都是后台权限没办法录屏，下载源码去掉这两个权限，是否会导致异常呢？

**Comment by mayzs** [comment]
这两个权限是适配 14 的时候添加的, 如果你想去掉,可以将targetSdk 降低, 否则会引起闪退

**Comment by mayzs** [comment]
1.2.0 版本使用 Worker 替换了AlarmManager, 去除了SCHEDULE_EXACT_ALARM,和USE_EXACT_ALARM两个权限
